name: jsonplaceholder_example
description: JSON Placeholder Example App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_data:
    path: ../../flutter_data
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
