name: flutter_data
description: >
  The seamless way to work with persistent data models in Flutter. Inspired by
  Ember Data and ActiveRecord.
version: 0.5.19
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.39.5
  async: ^2.4.0
  build: ^1.3.0
  build_resolvers: ^1.3.11
  collection: ^1.14.13
  data_state: ^0.3.7
  equatable: ^1.2.5
  glob: ^1.2.0
  hive: ^1.4.4+1
  http: ^0.12.2
  inflection2: ^0.4.3
  meta: ^1.1.8
  path: ^1.6.4
  pubspec_parse: ^0.1.5
  riverpod: ">=0.11.0 <1.0.0"
  source_gen: ^0.9.5
  state_notifier: ">= 0.6.0 <1.0.0"
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^0.10.11
  freezed: ^0.12.1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  matcher: ^0.12.6
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  source_gen_test: ^0.1.0
  test: ^1.9.4
  test_coverage: ^0.4.3
